spring.datasource.url=jdbc:mysql://mysql-2c90a643-carrier-con-database.h.aivencloud.com:12553/defaultdb?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



razorpay.key.id=rzp_test_YourKeyIdHere
razorpay.key.secret=YourSecretKeyHere

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=insconamankumar@gmail.com
spring.mail.password=ymxgxopfvzsnuroq

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

server.port=8000


